ALTER TABLE users
    ADD COLUMN firstname VARCHAR(100) NOT NULL AFTER email,
    ADD COLUMN lastname VARCHAR(100) NOT NULL AFTER firstname,
    ADD COLUMN phone VARCHAR(20) AFTER lastname,
    ADD COLUMN address VARCHAR(255) AFTER phone,
    ADD COLUMN postcode VARCHAR(10) AFTER address,
    ADD COLUMN city VARCHAR(100) AFTER postcode,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at,
    ADD COLUMN is_admin BOOLEAN DEFAULT FALSE AFTER updated_at; 